### ISSUE TITLE
Its written on C#

### ISSUE THREAD

**Issue by Randomneo** [ClassTerr/Game2048#1]
Its better rewrite on Python

**Comment by ClassTerr** [comment]
If you think so, I'm open for community contributions. 
You can send a PR to this repository if you with to rewrite it to Python 👌😉.

**Comment by ClassTerr** [comment]
@Randomneo If you think so, I'm open for community contributions.
You can send a PR to this repository if you with to rewrite it to Python 👌😉.

**Comment by ClassTerr** [comment]
@Randomneo If you think so, I'm open for community contributions.
You can send a PR to this repository if you wish to rewrite it with Python 👌😉.
